const SITE_ID = "waldorf-math";
const SUBJECT_ID = "math";
const SHARED_DB_VERSION = "v1";

const lessons = [
  {
    id: "g7-percent-base",
    activityKey: "g7-math-percent-base",
    grade: "Grade 7",
    block: "Percents",
    title: "Finding the Base",
    time: "14 min",
    sourceFocus: "Grade 7 percent work: move from finding a percent of a number to finding the whole.",
    teacherAim:
      "Students practice inverse percent thinking before formal algebra: if a part is a known percent, the whole can be rebuilt.",
    rhythm: ["25% means one quarter.", "If 36 is one quarter, the whole is four quarters.", "Check by taking the percent again."],
    prompt: "A class raised 42 dollars. This was 35% of its fair-day goal. What was the whole goal?",
    correction:
      "35% is 35/100. Divide 42 by 0.35 to rebuild the whole goal, then check that 35% of your answer is 42.",
    answerType: "number",
    answer: 120,
    tolerance: 0,
    suffix: "dollars",
  },
  {
    id: "g7-compound-interest",
    activityKey: "g7-math-compound-interest",
    grade: "Grade 7",
    block: "Business Math",
    title: "Simple and Compound Interest",
    time: "16 min",
    sourceFocus: "Grade 7 compound interest: compound annually by repeated year-by-year percent growth.",
    teacherAim:
      "Students compare simple interest with compound interest without using the later exponential-growth formula.",
    rhythm: ["Start with the principal.", "Find this year's interest.", "Add it before finding the next year's interest."],
    prompt:
      "Mara saves 200 dollars at 5% interest compounded annually. What is the balance after 2 years?",
    correction:
      "Year 1 earns 10 dollars, so the balance is 210. Year 2 earns 5% of 210, which is 10.50. Add that to 210.",
    answerType: "number",
    answer: 220.5,
    tolerance: 0.01,
    suffix: "dollars",
  },
  {
    id: "g7-ratio-whole",
    activityKey: "g7-math-ratio-whole",
    grade: "Grade 7",
    block: "Ratios",
    title: "Sharing by Ratio",
    time: "12 min",
    sourceFocus: "Grade 7 ratios: interpret parts of a whole before solving proportion equations.",
    teacherAim:
      "Students see a ratio as parts of a whole and use fraction-of-the-whole reasoning.",
    rhythm: ["Add the ratio parts.", "Name each share as part of the whole.", "Multiply the whole by that part."],
    prompt: "A garden bed has red and yellow flowers in a ratio of 2:3. There are 45 flowers altogether. How many are yellow?",
    correction:
      "The ratio has 5 total parts. Yellow is 3 of those 5 parts, so find 3/5 of 45.",
    answerType: "number",
    answer: 27,
    tolerance: 0,
    suffix: "yellow flowers",
  },
  {
    id: "g7-rate-speed",
    activityKey: "g7-math-rate-speed",
    grade: "Grade 7",
    block: "Rates",
    title: "Average Speed",
    time: "15 min",
    sourceFocus: "Grade 7 rate problems: build intuition for when to multiply and when to divide.",
    teacherAim:
      "Students convert time units and divide total distance by total time to find a rate.",
    rhythm: ["Rate means amount per one.", "Change minutes into hours.", "Divide distance by hours."],
    prompt: "A cyclist travels 6 miles in 15 minutes. What is the cyclist's average speed in miles per hour?",
    correction:
      "15 minutes is 1/4 hour. A rate in miles per hour asks how far in one hour, so divide 6 by 1/4.",
    answerType: "number",
    answer: 24,
    tolerance: 0,
    suffix: "mph",
  },
  {
    id: "g7-negative-numbers",
    activityKey: "g7-math-negative-numbers",
    grade: "Grade 7",
    block: "Algebra",
    title: "Positive and Negative Numbers",
    time: "10 min",
    sourceFocus: "Grade 7 algebra main lesson: careful practice with all four operations using signed numbers.",
    teacherAim:
      "Students work with negative numbers as number relationships, then check by reversing operations.",
    rhythm: ["A negative times a positive is negative.", "A negative times a negative is positive.", "Check the sign before the size."],
    prompt: "Find the value of -8 x 7 + 18.",
    correction:
      "First multiply: -8 x 7 = -56. Then add 18, moving 18 steps toward zero.",
    answerType: "number",
    answer: -38,
    tolerance: 0,
  },
  {
    id: "g7-expression-like-terms",
    activityKey: "g7-math-expression-like-terms",
    grade: "Grade 7",
    block: "Algebra",
    title: "Combining Like Terms",
    time: "13 min",
    sourceFocus: "Grade 7 algebra: develop clear form while simplifying expressions.",
    teacherAim:
      "Students separate unlike terms and constants, then simplify with neat visible steps.",
    rhythm: ["Gather the same letters.", "Gather plain numbers.", "Keep unlike terms separate."],
    prompt: "Simplify: 6k - 3 + 4k - 11. Write the simplified expression.",
    correction:
      "Combine 6k and 4k to make 10k. Combine -3 and -11 to make -14.",
    answerType: "expression",
    acceptedAnswers: ["10k-14", "10k - 14"],
  },
  {
    id: "g7-equation-balance",
    activityKey: "g7-math-equation-balance",
    grade: "Grade 7",
    block: "Algebra",
    title: "Balance the Equation",
    time: "14 min",
    sourceFocus: "Grade 7 algebra: solve equations by doing the same thing to both sides.",
    teacherAim:
      "Students use the golden rule of equations and verify the value by substitution.",
    rhythm: ["Keep the equal sign balanced.", "Move constants together.", "Divide last."],
    prompt: "Solve for x: 5x - 2 = 3x + 8.",
    correction:
      "Subtract 3x from both sides to get 2x - 2 = 8. Add 2 to both sides, then divide by 2.",
    answerType: "number",
    answer: 5,
    tolerance: 0,
  },
  {
    id: "g7-gauss-sum",
    activityKey: "g7-math-gauss-sum",
    grade: "Grade 7",
    block: "Formulas",
    title: "Gauss's Sum",
    time: "16 min",
    sourceFocus: "Grade 7 formulas: use first, last, and number of terms to sum an arithmetic sequence.",
    teacherAim:
      "Students experience a formula as condensed thinking rather than a rule to memorize.",
    rhythm: ["Pair first with last.", "Count how many numbers.", "Use half the count times the pair sum."],
    prompt: "Find the sum of 12 + 15 + 18 + ... + 48.",
    correction:
      "The sequence has 13 numbers. First plus last is 60. Use 13 x 60 / 2.",
    answerType: "number",
    answer: 390,
    tolerance: 0,
  },
  {
    id: "g7-table-square-products",
    activityKey: "g7-math-table-square-products",
    grade: "Grade 7",
    block: "Arithmetic Review",
    title: "Multiplication Table Thinking",
    time: "10 min",
    sourceFocus: "Multiplication table fluency from the 1-12 table template.",
    teacherAim:
      "Students rebuild a multiplication fact through doubling and symmetry instead of guessing.",
    examplePt:
      "Exemplo: para 6 x 8, pense 6 x 4 = 24. Dobrar 24 dá 48, então 6 x 8 = 48. Também podemos verificar: 8 x 6 = 48.",
    rhythm: ["Use a fact you know.", "Double or halve when it helps.", "Check by turning the factors around."],
    prompt: "Complete the steps for 7 x 8. Then give the final product.",
    guidedSteps: [
      { label: "Passo 1: Calcule 7 x 4.", answerType: "number", answer: 28 },
      { label: "Passo 2: Dobre o resultado para chegar a 7 x 8.", answerType: "number", answer: 56 },
      { label: "Passo 3: Verifique: 8 x 7 =", answerType: "number", answer: 56 },
    ],
    correction: "Respostas corretas: 7 x 4 = 28; dobrando 28 obtemos 56; 8 x 7 também é 56.",
    answerType: "number",
    answer: 56,
    tolerance: 0,
  },
  {
    id: "g7-missing-digit",
    activityKey: "g7-math-missing-digit",
    grade: "Grade 7",
    block: "Puzzles",
    title: "Missing Digit Multiplication",
    time: "12 min",
    sourceFocus: "Missing-digit multiplication puzzles and digit arithmetic.",
    teacherAim:
      "Students reason from place value, carry digits, and multiplication facts before naming the missing digit.",
    examplePt:
      "Exemplo: em 3? x 4 = 148, olhe primeiro para as unidades. 4 x ? termina em 8, então ? pode ser 2 ou 7. Testando 37 x 4 = 148, o dígito faltante é 7.",
    rhythm: ["Start with the ones column.", "Use the carry.", "Check the whole multiplication."],
    prompt: "Find the missing digit in 4? x 6 = 276. Then write the complete two-digit number.",
    guidedSteps: [
      { label: "Passo 1: Qual digit makes 6 x ? end in 6?", answerType: "number", answer: 6 },
      { label: "Passo 2: 6 x 6 = 36, so what carry goes to the tens column?", answerType: "number", answer: 3 },
      { label: "Passo 3: Check the tens: 6 x 4 + 3 =", answerType: "number", answer: 27 },
    ],
    correction: "Respostas corretas: o dígito é 6; o carry é 3; 6 x 4 + 3 = 27; o número completo é 46.",
    answerType: "number",
    answer: 46,
    tolerance: 0,
  },
  {
    id: "g7-fraction-common-denominator",
    activityKey: "g7-math-fraction-common-denominator",
    grade: "Grade 7",
    block: "Fractions",
    title: "Common Denominator Addition",
    time: "15 min",
    sourceFocus: "Fraction addition and fraction-decimal review sheets.",
    teacherAim:
      "Students show denominator choice, equivalent fractions, and the final mixed-number result.",
    examplePt:
      "Exemplo: para 1/3 + 1/4, use denominador 12. Então 1/3 = 4/12 e 1/4 = 3/12. Somando: 7/12.",
    rhythm: ["Choose one common denominator.", "Rewrite both fractions.", "Add numerators and keep the denominator."],
    prompt: "Add 5/6 + 3/8. Complete each step before the final answer.",
    guidedSteps: [
      { label: "Passo 1: Escolha um denominador comum.", answerType: "number", answer: 24 },
      { label: "Passo 2: Rewrite 5/6 as twenty-fourths.", answerType: "expression", acceptedAnswers: ["20/24"] },
      { label: "Passo 3: Rewrite 3/8 as twenty-fourths.", answerType: "expression", acceptedAnswers: ["9/24"] },
      { label: "Passo 4: Add the numerators.", answerType: "expression", acceptedAnswers: ["29/24"] },
    ],
    correction: "Respostas corretas: denominador comum 24; 5/6 = 20/24; 3/8 = 9/24; soma = 29/24 = 1 5/24.",
    answerType: "expression",
    acceptedAnswers: ["29/24", "1 5/24", "1+5/24"],
  },
  {
    id: "g7-decimal-division-shift",
    activityKey: "g7-math-decimal-division-shift",
    grade: "Grade 7",
    block: "Decimals",
    title: "Make the Divisor Whole",
    time: "14 min",
    sourceFocus: "Decimal division review: fix the divisor by moving decimal places before dividing.",
    teacherAim:
      "Students transform an equivalent division problem and estimate before calculating.",
    examplePt:
      "Exemplo: 36 ÷ 0.09 fica 3600 ÷ 9, porque movemos as duas vírgulas duas casas para a direita. A resposta é 400.",
    rhythm: ["Move both decimal points the same number of places.", "Make the divisor whole.", "Estimate before dividing."],
    prompt: "Solve 21.3 ÷ 5.68. Round to the nearest hundredth.",
    guidedSteps: [
      { label: "Passo 1: Move decimal points how many places?", answerType: "number", answer: 2 },
      { label: "Passo 2: The equivalent problem is 2130 ÷", answerType: "number", answer: 568 },
      { label: "Passo 3: Estimate the answer to the nearest whole number.", answerType: "number", answer: 4, tolerance: 1 },
    ],
    correction: "Respostas corretas: mova 2 casas; 21.3 ÷ 5.68 = 2130 ÷ 568; o resultado é aproximadamente 3.75.",
    answerType: "number",
    answer: 3.75,
    tolerance: 0.01,
  },
  {
    id: "g7-unit-cost",
    activityKey: "g7-math-unit-cost",
    grade: "Grade 7",
    block: "Unit Cost",
    title: "Which Price Is Better?",
    time: "12 min",
    sourceFocus: "Unit cost problems from the arithmetic review sheets.",
    teacherAim:
      "Students divide total cost by quantity and compare one-unit prices.",
    examplePt:
      "Exemplo: se 5 laranjas custam R$10,00, cada laranja custa R$2,00, porque 10 ÷ 5 = 2.",
    rhythm: ["Find the price for one item.", "Compare equal units.", "Choose the smaller unit price."],
    prompt: "Store A sells 6 pencils for $4.20. Store B sells 10 pencils for $6.50. Which store is cheaper per pencil?",
    guidedSteps: [
      { label: "Passo 1: Store A unit price: 4.20 ÷ 6 =", answerType: "number", answer: 0.7, tolerance: 0.001 },
      { label: "Passo 2: Store B unit price: 6.50 ÷ 10 =", answerType: "number", answer: 0.65, tolerance: 0.001 },
      { label: "Passo 3: Which unit price is smaller, A or B?", answerType: "expression", acceptedAnswers: ["b", "storeb", "store b"] },
    ],
    correction: "Respostas corretas: Store A = $0.70 por lápis; Store B = $0.65 por lápis; Store B é mais barato.",
    answerType: "expression",
    acceptedAnswers: ["b", "storeb", "store b"],
  },
  {
    id: "g7-divisibility-check",
    activityKey: "g7-math-divisibility-check",
    grade: "Grade 7",
    block: "Divisibility",
    title: "Divisibility Rules",
    time: "11 min",
    sourceFocus: "Divisibility by 2, 3, 4, 5, 9, and 10.",
    teacherAim:
      "Students use digit tests and explain which divisors work.",
    examplePt:
      "Exemplo: 732 é divisível por 3 porque 7 + 3 + 2 = 12, e 12 é divisível por 3. Não é divisível por 5 porque não termina em 0 ou 5.",
    rhythm: ["Check the last digit.", "Add the digits.", "Check the last two digits for 4."],
    prompt: "Which of 2, 3, 4, 5, 9, and 10 divide 85,734 evenly?",
    guidedSteps: [
      { label: "Passo 1: Add the digits: 8 + 5 + 7 + 3 + 4 =", answerType: "number", answer: 27 },
      { label: "Passo 2: Is the number even? Answer yes or no.", answerType: "expression", acceptedAnswers: ["yes", "sim"] },
      { label: "Passo 3: Are the last two digits, 34, divisible by 4? Answer yes or no.", answerType: "expression", acceptedAnswers: ["no", "nao", "não"] },
    ],
    correction: "Respostas corretas: soma dos dígitos = 27; o número é par; 34 não é divisível por 4. Divisores: 2, 3 e 9.",
    answerType: "expression",
    acceptedAnswers: ["2,3,9", "2 3 9", "2;3;9"],
  },
  {
    id: "g7-reduce-fraction",
    activityKey: "g7-math-reduce-fraction",
    grade: "Grade 7",
    block: "Fractions",
    title: "Reduce a Large Fraction",
    time: "12 min",
    sourceFocus: "Reducing large fractions from Grade 7 arithmetic review.",
    teacherAim:
      "Students reduce in visible stages instead of trying to jump to the answer.",
    examplePt:
      "Exemplo: 36/48 pode ser dividido por 12. Então 36 ÷ 12 = 3 e 48 ÷ 12 = 4, logo 36/48 = 3/4.",
    rhythm: ["Find a common factor.", "Divide top and bottom by the same number.", "Keep reducing until no factor remains."],
    prompt: "Reduce 7560/8100 to lowest terms.",
    guidedSteps: [
      { label: "Passo 1: Divide top and bottom by 180. New numerator:", answerType: "number", answer: 42 },
      { label: "Passo 2: Divide top and bottom by 180. New denominator:", answerType: "number", answer: 45 },
      { label: "Passo 3: Reduce 42/45 by 3.", answerType: "expression", acceptedAnswers: ["14/15"] },
    ],
    correction: "Respostas corretas: 7560/8100 ÷ 180 = 42/45; depois 42/45 ÷ 3 = 14/15.",
    answerType: "expression",
    acceptedAnswers: ["14/15"],
  },
  {
    id: "g7-repeating-decimal-fraction",
    activityKey: "g7-math-repeating-decimal-fraction",
    grade: "Grade 7",
    block: "Repeating Decimals",
    title: "Repeating Decimal to Fraction",
    time: "15 min",
    sourceFocus: "Converting repeating decimals into fractions.",
    teacherAim:
      "Students connect a repeating block to 9s in the denominator and then reduce.",
    examplePt:
      "Exemplo: 0.27 repetindo vira 27/99, porque dois algarismos repetem. Depois reduzimos: 27/99 = 3/11.",
    rhythm: ["Count the repeating digits.", "Use the same number of 9s.", "Reduce the fraction."],
    prompt: "Convert 0.36 repeating to a fraction in lowest terms.",
    guidedSteps: [
      { label: "Passo 1: How many digits repeat?", answerType: "number", answer: 2 },
      { label: "Passo 2: Write the first fraction before reducing.", answerType: "expression", acceptedAnswers: ["36/99"] },
      { label: "Passo 3: Divide numerator and denominator by 9.", answerType: "expression", acceptedAnswers: ["4/11"] },
    ],
    correction: "Respostas corretas: dois dígitos repetem; 0.363636... = 36/99; reduzindo por 9 obtemos 4/11.",
    answerType: "expression",
    acceptedAnswers: ["4/11"],
  },
];

const sharedDbShape = {
  siteSlug: SITE_ID,
  subjectSlug: SUBJECT_ID,
  accountNamespace: "Waldorf English Pathway Supabase",
  accountFields: ["auth.users.email", "guardian_profiles.user_id", "learners.nickname", "learners.school_year"],
  progressFields: ["objective_responses.learner_id", "objective_responses.activity_key", "activity_progress.completed"],
};

window.lessons = lessons;
window.sharedDbShape = sharedDbShape;
