const SITE_ID = "waldorf-math";
const SUBJECT_ID = "math";
const SHARED_DB_VERSION = "v1";

const lessons = [
  {
    id: "g7-percent-base",
    activityKey: "g7-math-percent-base",
    grade: "Grade 7",
    block: "Percents",
    title: "Finding the Base",
    time: "14 min",
    sourceFocus: "Grade 7 percent work: move from finding a percent of a number to finding the whole.",
    teacherAim:
      "Students practice inverse percent thinking before formal algebra: if a part is a known percent, the whole can be rebuilt.",
    memoryRefresh: {
      idea: "A percent problem has a base, which is the whole amount the percent is taken from. Finding the base means working backward from the part.",
      method: ["Turn the percent into a decimal or fraction.", "Ask what whole number would give this part.", "Use the inverse operation: divide by the decimal, or multiply by the reciprocal.", "Check by taking the percent of your answer."],
      example: "If 18 is 30% of a number, think 18 ÷ 0.30 = 60. Check: 30% of 60 is 18.",
    },
    rhythm: ["25% means one quarter.", "If 36 is one quarter, the whole is four quarters.", "Check by taking the percent again."],
    prompt: "A class raised 42 dollars. This was 35% of its fair-day goal. What was the whole goal?",
    correction:
      "35% is 35/100. Divide 42 by 0.35 to rebuild the whole goal, then check that 35% of your answer is 42.",
    answerType: "number",
    answer: 120,
    tolerance: 0,
    suffix: "dollars",
  },
  {
    id: "g7-compound-interest",
    activityKey: "g7-math-compound-interest",
    grade: "Grade 7",
    block: "Business Math",
    title: "Simple and Compound Interest",
    time: "16 min",
    sourceFocus: "Grade 7 compound interest: compound annually by repeated year-by-year percent growth.",
    teacherAim:
      "Students compare simple interest with compound interest without using the later exponential-growth formula.",
    memoryRefresh: {
      idea: "Simple interest uses the original amount every year. Compound interest grows year by year because each new balance earns the next year's interest.",
      method: ["Start with the principal.", "Find one year's interest from the current balance.", "Add the interest to make a new balance.", "Repeat for each year, rounding money to cents when needed."],
      example: "$100 at 10% compounded yearly becomes $110 after year 1. Year 2 earns 10% of $110, so the balance becomes $121.",
    },
    rhythm: ["Start with the principal.", "Find this year's interest.", "Add it before finding the next year's interest."],
    prompt:
      "Mara saves 200 dollars at 5% interest compounded annually. What is the balance after 2 years?",
    correction:
      "Year 1 earns 10 dollars, so the balance is 210. Year 2 earns 5% of 210, which is 10.50. Add that to 210.",
    answerType: "number",
    answer: 220.5,
    tolerance: 0.01,
    suffix: "dollars",
  },
  {
    id: "g7-ratio-whole",
    activityKey: "g7-math-ratio-whole",
    grade: "Grade 7",
    block: "Ratios",
    title: "Sharing by Ratio",
    time: "12 min",
    sourceFocus: "Grade 7 ratios: interpret parts of a whole before solving proportion equations.",
    teacherAim:
      "Students see a ratio as parts of a whole and use fraction-of-the-whole reasoning.",
    memoryRefresh: {
      idea: "A ratio names shares. The total number of ratio parts represents the whole group.",
      method: ["Add the parts in the ratio.", "Decide which part belongs to the question.", "Write that share as a fraction of the whole.", "Multiply the total by that fraction."],
      example: "In a 1:4 ratio, there are 5 parts. The second share is 4/5 of the whole, so if the whole is 30, the second share is 24.",
    },
    rhythm: ["Add the ratio parts.", "Name each share as part of the whole.", "Multiply the whole by that part."],
    prompt: "A garden bed has red and yellow flowers in a ratio of 2:3. There are 45 flowers altogether. How many are yellow?",
    correction:
      "The ratio has 5 total parts. Yellow is 3 of those 5 parts, so find 3/5 of 45.",
    answerType: "number",
    answer: 27,
    tolerance: 0,
    suffix: "yellow flowers",
  },
  {
    id: "g7-rate-speed",
    activityKey: "g7-math-rate-speed",
    grade: "Grade 7",
    block: "Rates",
    title: "Average Speed",
    time: "15 min",
    sourceFocus: "Grade 7 rate problems: build intuition for when to multiply and when to divide.",
    teacherAim:
      "Students convert time units and divide total distance by total time to find a rate.",
    memoryRefresh: {
      idea: "A rate tells how much happens for one unit. Miles per hour asks how many miles happen in one hour.",
      method: ["Convert the time to hours.", "Ask whether you need distance, time, or speed.", "For speed, divide distance by time.", "Check whether the answer is reasonable for one hour."],
      example: "If 12 miles take 1/2 hour, then the one-hour speed is 12 ÷ 1/2 = 24 mph.",
    },
    rhythm: ["Rate means amount per one.", "Change minutes into hours.", "Divide distance by hours."],
    prompt: "A cyclist travels 6 miles in 15 minutes. What is the cyclist's average speed in miles per hour?",
    correction:
      "15 minutes is 1/4 hour. A rate in miles per hour asks how far in one hour, so divide 6 by 1/4.",
    answerType: "number",
    answer: 24,
    tolerance: 0,
    suffix: "mph",
  },
  {
    id: "g7-negative-numbers",
    activityKey: "g7-math-negative-numbers",
    grade: "Grade 7",
    block: "Algebra",
    title: "Positive and Negative Numbers",
    time: "10 min",
    sourceFocus: "Grade 7 algebra main lesson: careful practice with all four operations using signed numbers.",
    teacherAim:
      "Students work with negative numbers as number relationships, then check by reversing operations.",
    memoryRefresh: {
      idea: "Negative numbers are numbers below zero. In an expression, handle multiplication first and keep track of the sign before combining.",
      method: ["Do multiplication or division before addition.", "A negative times a positive is negative.", "A negative times a negative is positive.", "When adding a positive to a negative, move toward zero."],
      example: "-6 x 5 + 12 becomes -30 + 12, which is -18.",
    },
    rhythm: ["A negative times a positive is negative.", "A negative times a negative is positive.", "Check the sign before the size."],
    prompt: "Find the value of -8 x 7 + 18.",
    correction:
      "First multiply: -8 x 7 = -56. Then add 18, moving 18 steps toward zero.",
    answerType: "number",
    answer: -38,
    tolerance: 0,
  },
  {
    id: "g7-expression-like-terms",
    activityKey: "g7-math-expression-like-terms",
    grade: "Grade 7",
    block: "Algebra",
    title: "Combining Like Terms",
    time: "13 min",
    sourceFocus: "Grade 7 algebra: develop clear form while simplifying expressions.",
    teacherAim:
      "Students separate unlike terms and constants, then simplify with neat visible steps.",
    memoryRefresh: {
      idea: "Like terms have the same letter part. Plain numbers combine only with plain numbers.",
      method: ["Circle or gather terms with the same letter.", "Keep the sign attached to each term.", "Add or subtract the coefficients.", "Write unlike terms separately in a clean final expression."],
      example: "4m - 7 + 2m + 3 becomes 6m - 4.",
    },
    rhythm: ["Gather the same letters.", "Gather plain numbers.", "Keep unlike terms separate."],
    prompt: "Simplify: 6k - 3 + 4k - 11. Write the simplified expression.",
    correction:
      "Combine 6k and 4k to make 10k. Combine -3 and -11 to make -14.",
    answerType: "expression",
    acceptedAnswers: ["10k-14", "10k - 14"],
  },
  {
    id: "g7-equation-balance",
    activityKey: "g7-math-equation-balance",
    grade: "Grade 7",
    block: "Algebra",
    title: "Balance the Equation",
    time: "14 min",
    sourceFocus: "Grade 7 algebra: solve equations by doing the same thing to both sides.",
    teacherAim:
      "Students use the golden rule of equations and verify the value by substitution.",
    memoryRefresh: {
      idea: "An equation is a balance puzzle. Whatever you do to one side must also be done to the other side.",
      method: ["Move variable terms to one side by doing the same operation to both sides.", "Move plain numbers to the other side.", "Divide by the number multiplying the variable.", "Check by substituting the answer into the original equation."],
      example: "2x + 3 = 11. Subtract 3 from both sides: 2x = 8. Divide both sides by 2: x = 4.",
    },
    rhythm: ["Keep the equal sign balanced.", "Move constants together.", "Divide last."],
    prompt: "Solve for x: 5x - 2 = 3x + 8.",
    correction:
      "Subtract 3x from both sides to get 2x - 2 = 8. Add 2 to both sides, then divide by 2.",
    answerType: "number",
    answer: 5,
    tolerance: 0,
  },
  {
    id: "g7-gauss-sum",
    activityKey: "g7-math-gauss-sum",
    grade: "Grade 7",
    block: "Formulas",
    title: "Gauss's Sum",
    time: "16 min",
    sourceFocus: "Grade 7 formulas: use first, last, and number of terms to sum an arithmetic sequence.",
    teacherAim:
      "Students experience a formula as condensed thinking rather than a rule to memorize.",
    memoryRefresh: {
      idea: "A formula can hold a pattern in a short form. For a regular sequence, pair the first and last numbers.",
      method: ["Find the first number and last number.", "Count how many numbers are in the sequence.", "Add first plus last.", "Multiply by the number of terms, then divide by 2."],
      example: "For 2 + 4 + 6 + 8, first plus last is 10, there are 4 numbers, so 4 x 10 ÷ 2 = 20.",
    },
    rhythm: ["Pair first with last.", "Count how many numbers.", "Use half the count times the pair sum."],
    prompt: "Find the sum of 12 + 15 + 18 + ... + 48.",
    correction:
      "The sequence has 13 numbers. First plus last is 60. Use 13 x 60 / 2.",
    answerType: "number",
    answer: 390,
    tolerance: 0,
  },
  {
    id: "g7-table-square-products",
    activityKey: "g7-math-table-square-products",
    grade: "Grade 7",
    block: "Arithmetic Review",
    title: "Multiplication Table Thinking",
    time: "10 min",
    sourceFocus: "Multiplication table fluency from the 1-12 table template.",
    teacherAim:
      "Students rebuild a multiplication fact through doubling and symmetry instead of guessing.",
    memoryRefresh: {
      idea: "When a multiplication fact feels rusty, build it from a nearby fact you know well.",
      method: ["Choose an easier related fact.", "Double, halve, or add another group to reach the target fact.", "Use the turn-around fact to check.", "Write the final product only after the check makes sense."],
      example: "For 7 x 8, use 7 x 4 = 28, then double 28 to get 56.",
    },
    examplePt:
      "Example: for 6 x 8, think 6 x 4 = 24. Doubling 24 gives 48, so 6 x 8 = 48. We can also check: 8 x 6 = 48.",
    rhythm: ["Use a fact you know.", "Double or halve when it helps.", "Check by turning the factors around."],
    prompt: "Complete the steps for 7 x 8. Then give the final product.",
    guidedSteps: [
      { label: "Step 1: Calculate 7 x 4.", answerType: "number", answer: 28 },
      { label: "Step 2: Double the result to reach 7 x 8.", answerType: "number", answer: 56 },
      { label: "Step 3: Check: 8 x 7 =", answerType: "number", answer: 56 },
    ],
    correction: "Correct answers: 7 x 4 = 28; doubling 28 gives 56; 8 x 7 is also 56.",
    answerType: "number",
    answer: 56,
    tolerance: 0,
  },
  {
    id: "g7-missing-digit",
    activityKey: "g7-math-missing-digit",
    grade: "Grade 7",
    block: "Puzzles",
    title: "Missing Digit Multiplication",
    time: "12 min",
    sourceFocus: "Missing-digit multiplication puzzles and digit arithmetic.",
    teacherAim:
      "Students reason from place value, carry digits, and multiplication facts before naming the missing digit.",
    memoryRefresh: {
      idea: "Missing-digit multiplication is solved column by column. The ones column usually gives the first clue.",
      method: ["Look at the ones digit of the answer.", "Find which digit could make that ones digit.", "Include the carry into the tens column.", "Check the complete multiplication."],
      example: "In 2? x 3 = 78, the ones digit must make 3 x ? end in 8, so ? is 6. Then 26 x 3 = 78.",
    },
    examplePt:
      "Example: in 3? x 4 = 148, first look at the ones. 4 x ? ends in 8, so ? could be 2 or 7. Testing 37 x 4 = 148 shows the missing digit is 7.",
    rhythm: ["Start with the ones column.", "Use the carry.", "Check the whole multiplication."],
    prompt: "Find the missing digit in 4? x 6 = 276. Then write the complete two-digit number.",
    guidedSteps: [
      { label: "Step 1: Which digit makes 6 x ? end in 6?", answerType: "number", answer: 6 },
      { label: "Step 2: 6 x 6 = 36, so what carry goes to the tens column?", answerType: "number", answer: 3 },
      { label: "Step 3: Check the tens: 6 x 4 + 3 =", answerType: "number", answer: 27 },
    ],
    correction: "Correct answers: the digit is 6; the carry is 3; 6 x 4 + 3 = 27; the complete number is 46.",
    answerType: "number",
    answer: 46,
    tolerance: 0,
  },
  {
    id: "g7-fraction-common-denominator",
    activityKey: "g7-math-fraction-common-denominator",
    grade: "Grade 7",
    block: "Fractions",
    title: "Common Denominator Addition",
    time: "15 min",
    sourceFocus: "Fraction addition and fraction-decimal review sheets.",
    teacherAim:
      "Students show denominator choice, equivalent fractions, and the final mixed-number result.",
    memoryRefresh: {
      idea: "Fractions can be added only when the pieces have the same size. A common denominator makes the pieces match.",
      method: ["Choose a common denominator.", "Rewrite each fraction without changing its value.", "Add the numerators and keep the denominator.", "Reduce or write a mixed number if needed."],
      example: "1/3 + 1/6 becomes 2/6 + 1/6 = 3/6 = 1/2.",
    },
    examplePt:
      "Example: for 1/3 + 1/4, use denominator 12. Then 1/3 = 4/12 and 1/4 = 3/12. Adding gives 7/12.",
    rhythm: ["Choose one common denominator.", "Rewrite both fractions.", "Add numerators and keep the denominator."],
    prompt: "Add 5/6 + 3/8. Complete each step before the final answer.",
    guidedSteps: [
      { label: "Step 1: Choose a common denominator.", answerType: "number", answer: 24 },
      { label: "Step 2: Rewrite 5/6 as twenty-fourths.", answerType: "expression", acceptedAnswers: ["20/24"] },
      { label: "Step 3: Rewrite 3/8 as twenty-fourths.", answerType: "expression", acceptedAnswers: ["9/24"] },
      { label: "Step 4: Add the numerators.", answerType: "expression", acceptedAnswers: ["29/24"] },
    ],
    correction: "Correct answers: common denominator 24; 5/6 = 20/24; 3/8 = 9/24; sum = 29/24 = 1 5/24.",
    answerType: "expression",
    acceptedAnswers: ["29/24", "1 5/24", "1+5/24"],
  },
  {
    id: "g7-decimal-division-shift",
    activityKey: "g7-math-decimal-division-shift",
    grade: "Grade 7",
    block: "Decimals",
    title: "Make the Divisor Whole",
    time: "14 min",
    sourceFocus: "Decimal division review: fix the divisor by moving decimal places before dividing.",
    teacherAim:
      "Students transform an equivalent division problem and estimate before calculating.",
    memoryRefresh: {
      idea: "Decimal division gets easier when the divisor is a whole number. Move both decimal points the same number of places so the value of the division stays the same.",
      method: ["Count how many places move the divisor to a whole number.", "Move the dividend the same number of places.", "Divide the new numbers.", "Estimate first so you can catch a decimal-point mistake."],
      example: "4.8 ÷ 0.6 becomes 48 ÷ 6, so the answer is 8.",
    },
    examplePt:
      "Example: 36 ÷ 0.09 becomes 3600 ÷ 9 because we move both decimal points two places to the right. The answer is 400.",
    rhythm: ["Move both decimal points the same number of places.", "Make the divisor whole.", "Estimate before dividing."],
    prompt: "Solve 21.3 ÷ 5.68. Round to the nearest hundredth.",
    guidedSteps: [
      { label: "Step 1: Move decimal points how many places?", answerType: "number", answer: 2 },
      { label: "Step 2: The equivalent problem is 2130 ÷", answerType: "number", answer: 568 },
      { label: "Step 3: Estimate the answer to the nearest whole number.", answerType: "number", answer: 4, tolerance: 1 },
    ],
    correction: "Correct answers: move 2 places; 21.3 ÷ 5.68 = 2130 ÷ 568; the result is approximately 3.75.",
    answerType: "number",
    answer: 3.75,
    tolerance: 0.01,
  },
  {
    id: "g7-unit-cost",
    activityKey: "g7-math-unit-cost",
    grade: "Grade 7",
    block: "Unit Cost",
    title: "Which Price Is Better?",
    time: "12 min",
    sourceFocus: "Unit cost problems from the arithmetic review sheets.",
    teacherAim:
      "Students divide total cost by quantity and compare one-unit prices.",
    memoryRefresh: {
      idea: "Unit cost means the cost for one item. Once both choices are reduced to one item, the comparison is fair.",
      method: ["Divide total price by number of items.", "Do this for each store or option.", "Compare the same unit in both answers.", "Choose the smaller unit price for the better buy."],
      example: "If 4 notebooks cost $10, one notebook costs $10 ÷ 4 = $2.50.",
    },
    examplePt:
      "Example: if 5 oranges cost $10.00, each orange costs $2.00 because 10 ÷ 5 = 2.",
    rhythm: ["Find the price for one item.", "Compare equal units.", "Choose the smaller unit price."],
    prompt: "Store A sells 6 pencils for $4.20. Store B sells 10 pencils for $6.50. Which store is cheaper per pencil?",
    guidedSteps: [
      { label: "Step 1: Store A unit price: 4.20 ÷ 6 =", answerType: "number", answer: 0.7, tolerance: 0.001 },
      { label: "Step 2: Store B unit price: 6.50 ÷ 10 =", answerType: "number", answer: 0.65, tolerance: 0.001 },
      { label: "Step 3: Which unit price is smaller, A or B?", answerType: "expression", acceptedAnswers: ["b", "storeb", "store b"] },
    ],
    correction: "Correct answers: Store A = $0.70 per pencil; Store B = $0.65 per pencil; Store B is cheaper.",
    answerType: "expression",
    acceptedAnswers: ["b", "storeb", "store b"],
  },
  {
    id: "g7-divisibility-check",
    activityKey: "g7-math-divisibility-check",
    grade: "Grade 7",
    block: "Divisibility",
    title: "Divisibility Rules",
    time: "11 min",
    sourceFocus: "Divisibility by 2, 3, 4, 5, 9, and 10.",
    teacherAim:
      "Students use digit tests and explain which divisors work.",
    memoryRefresh: {
      idea: "Divisibility rules are quick checks that use digits instead of long division.",
      method: ["Check 2 with the last digit.", "Check 3 and 9 by adding digits.", "Check 4 with the last two digits.", "Check 5 and 10 by the ending digit."],
      example: "732 is divisible by 2 because it is even, by 3 because 7 + 3 + 2 = 12, and by 4 because 32 is divisible by 4.",
    },
    examplePt:
      "Example: 732 is divisible by 3 because 7 + 3 + 2 = 12, and 12 is divisible by 3. It is not divisible by 5 because it does not end in 0 or 5.",
    rhythm: ["Check the last digit.", "Add the digits.", "Check the last two digits for 4."],
    prompt: "Which of 2, 3, 4, 5, 9, and 10 divide 85,734 evenly?",
    guidedSteps: [
      { label: "Step 1: Add the digits: 8 + 5 + 7 + 3 + 4 =", answerType: "number", answer: 27 },
      { label: "Step 2: Is the number even? Answer yes or no.", answerType: "expression", acceptedAnswers: ["yes", "sim"] },
      { label: "Step 3: Are the last two digits, 34, divisible by 4? Answer yes or no.", answerType: "expression", acceptedAnswers: ["no", "nao", "não"] },
    ],
    correction: "Correct answers: digit sum = 27; the number is even; 34 is not divisible by 4. Divisors: 2, 3, and 9.",
    answerType: "expression",
    acceptedAnswers: ["2,3,9", "2 3 9", "2;3;9"],
  },
  {
    id: "g7-reduce-fraction",
    activityKey: "g7-math-reduce-fraction",
    grade: "Grade 7",
    block: "Fractions",
    title: "Reduce a Large Fraction",
    time: "12 min",
    sourceFocus: "Reducing large fractions from Grade 7 arithmetic review.",
    teacherAim:
      "Students reduce in visible stages instead of trying to jump to the answer.",
    memoryRefresh: {
      idea: "Reducing a fraction means dividing the numerator and denominator by the same factor so the value stays equal.",
      method: ["Look for an easy common factor.", "Divide top and bottom by that factor.", "Repeat until no common factor remains.", "Check that the numerator and denominator are still whole numbers."],
      example: "48/60 can be divided by 12 to get 4/5.",
    },
    examplePt:
      "Example: 36/48 can be divided by 12. Then 36 ÷ 12 = 3 and 48 ÷ 12 = 4, so 36/48 = 3/4.",
    rhythm: ["Find a common factor.", "Divide top and bottom by the same number.", "Keep reducing until no factor remains."],
    prompt: "Reduce 7560/8100 to lowest terms.",
    guidedSteps: [
      { label: "Step 1: Divide top and bottom by 180. New numerator:", answerType: "number", answer: 42 },
      { label: "Step 2: Divide top and bottom by 180. New denominator:", answerType: "number", answer: 45 },
      { label: "Step 3: Reduce 42/45 by 3.", answerType: "expression", acceptedAnswers: ["14/15"] },
    ],
    correction: "Correct answers: 7560/8100 ÷ 180 = 42/45; then 42/45 ÷ 3 = 14/15.",
    answerType: "expression",
    acceptedAnswers: ["14/15"],
  },
  {
    id: "g7-repeating-decimal-fraction",
    activityKey: "g7-math-repeating-decimal-fraction",
    grade: "Grade 7",
    block: "Repeating Decimals",
    title: "Repeating Decimal to Fraction",
    time: "15 min",
    sourceFocus: "Converting repeating decimals into fractions.",
    teacherAim:
      "Students connect a repeating block to 9s in the denominator and then reduce.",
    memoryRefresh: {
      idea: "A repeating decimal can often be turned into a fraction with 9s in the denominator. The number of repeating digits tells how many 9s to use.",
      method: ["Count the repeating digits.", "Put the repeating block over the same number of 9s.", "Reduce the fraction.", "Check by thinking whether the decimal repeats with the same block."],
      example: "0.45 repeating has two repeating digits, so it becomes 45/99, which reduces to 5/11.",
    },
    examplePt:
      "Example: repeating 0.27 becomes 27/99 because two digits repeat. Then we reduce: 27/99 = 3/11.",
    rhythm: ["Count the repeating digits.", "Use the same number of 9s.", "Reduce the fraction."],
    prompt: "Convert 0.36 repeating to a fraction in lowest terms.",
    guidedSteps: [
      { label: "Step 1: How many digits repeat?", answerType: "number", answer: 2 },
      { label: "Step 2: Write the first fraction before reducing.", answerType: "expression", acceptedAnswers: ["36/99"] },
      { label: "Step 3: Divide numerator and denominator by 9.", answerType: "expression", acceptedAnswers: ["4/11"] },
    ],
    correction: "Correct answers: two digits repeat; 0.363636... = 36/99; reducing by 9 gives 4/11.",
    answerType: "expression",
    acceptedAnswers: ["4/11"],
  },
];

const lessonTranslations = {
  "g7-percent-base": {
    grade: "7o ano",
    block: "Porcentagens",
    title: "Encontrando o todo",
    sourceFocus: "Trabalho de porcentagem do 7o ano: passar de encontrar uma porcentagem de um numero para encontrar o todo.",
    teacherAim:
      "Os estudantes praticam o pensamento inverso da porcentagem antes da algebra formal: se uma parte e uma porcentagem conhecida, o todo pode ser reconstruido.",
    memoryRefresh: {
      idea: "Um problema de porcentagem tem uma base: o todo do qual a porcentagem foi tirada. Encontrar a base significa trabalhar de volta a partir da parte.",
      method: ["Transforme a porcentagem em decimal ou fracao.", "Pergunte qual todo produziria essa parte.", "Use a operacao inversa: divida pelo decimal ou multiplique pelo reciproco.", "Confira calculando a porcentagem da sua resposta."],
      example: "Se 18 e 30% de um numero, pense 18 dividido por 0.30 = 60. Confira: 30% de 60 e 18.",
    },
    rhythm: ["35% significa 35 de cada 100.", "Divida a parte pela forma decimal da porcentagem.", "Confira calculando a porcentagem novamente."],
    prompt: "Uma turma arrecadou 42 dolares. Isso foi 35% da meta da feira. Qual era a meta total?",
    correction:
      "35% e 35/100. Divida 42 por 0.35 para reconstruir a meta total, depois confira se 35% da sua resposta e 42.",
  },
  "g7-compound-interest": {
    grade: "7o ano",
    block: "Matematica financeira",
    title: "Juros simples e compostos",
    sourceFocus: "Juros compostos do 7o ano: composicao anual por crescimento percentual ano a ano.",
    teacherAim:
      "Os estudantes comparam juros simples e compostos sem usar ainda a formula posterior de crescimento exponencial.",
    memoryRefresh: {
      idea: "Juros simples usam o valor inicial todos os anos. Juros compostos crescem ano a ano, porque cada novo saldo rende os juros do ano seguinte.",
      method: ["Comece com o capital inicial.", "Calcule os juros de um ano usando o saldo atual.", "Some os juros para formar o novo saldo.", "Repita para cada ano, arredondando dinheiro para centavos quando necessario."],
      example: "$100 a 10% ao ano vira $110 depois do ano 1. No ano 2, 10% de $110 e $11, entao o saldo vira $121.",
    },
    rhythm: ["Comece com o capital inicial.", "Encontre os juros deste ano.", "Some os juros antes de calcular os juros do proximo ano."],
    prompt: "Mara guarda 200 dolares com juros de 5% ao ano, compostos anualmente. Qual e o saldo depois de 2 anos?",
    correction:
      "No ano 1, rende 10 dolares, entao o saldo vira 210. No ano 2, 5% de 210 e 10.50. Some isso a 210.",
  },
  "g7-ratio-whole": {
    grade: "7o ano",
    block: "Razoes",
    title: "Dividindo por razao",
    sourceFocus: "Razoes no 7o ano: interpretar partes de um todo antes de resolver equacoes de proporcao.",
    teacherAim:
      "Os estudantes veem a razao como partes de um todo e usam o raciocinio de fracao do todo.",
    memoryRefresh: {
      idea: "Uma razao nomeia partes. A soma das partes da razao representa o grupo inteiro.",
      method: ["Some as partes da razao.", "Veja qual parte a pergunta pede.", "Escreva essa parte como fracao do todo.", "Multiplique o total por essa fracao."],
      example: "Na razao 1:4, ha 5 partes. A segunda parte e 4/5 do todo; se o todo e 30, essa parte vale 24.",
    },
    rhythm: ["Some as partes da razao.", "Nomeie cada parte como fracao do todo.", "Multiplique o todo por essa parte."],
    prompt: "Um canteiro tem flores vermelhas e amarelas na razao 2:3. Ha 45 flores ao todo. Quantas sao amarelas?",
    correction:
      "A razao tem 5 partes ao todo. As amarelas sao 3 dessas 5 partes, entao encontre 3/5 de 45.",
  },
  "g7-rate-speed": {
    grade: "7o ano",
    block: "Taxas",
    title: "Velocidade media",
    sourceFocus: "Problemas de taxa do 7o ano: desenvolver intuicao para quando multiplicar e quando dividir.",
    teacherAim:
      "Os estudantes convertem unidades de tempo e dividem a distancia total pelo tempo total para encontrar uma taxa.",
    memoryRefresh: {
      idea: "Uma taxa diz quanto acontece em uma unidade. Milhas por hora pergunta quantas milhas acontecem em uma hora.",
      method: ["Converta o tempo para horas.", "Pergunte se voce precisa de distancia, tempo ou velocidade.", "Para velocidade, divida distancia por tempo.", "Confira se a resposta faz sentido para uma hora."],
      example: "Se 12 milhas levam 1/2 hora, a velocidade em uma hora e 12 dividido por 1/2 = 24 mph.",
    },
    rhythm: ["Taxa significa quantidade por uma unidade.", "Transforme minutos em horas.", "Divida a distancia pelas horas."],
    prompt: "Um ciclista percorre 6 milhas em 15 minutos. Qual e a velocidade media em milhas por hora?",
    correction:
      "15 minutos e 1/4 de hora. Uma taxa em milhas por hora pergunta a distancia em uma hora, entao divida 6 por 1/4.",
  },
  "g7-negative-numbers": {
    grade: "7o ano",
    block: "Algebra",
    title: "Numeros positivos e negativos",
    sourceFocus: "Aula principal de algebra do 7o ano: pratica cuidadosa das quatro operacoes com numeros com sinal.",
    teacherAim:
      "Os estudantes trabalham com numeros negativos como relacoes numericas e depois conferem invertendo as operacoes.",
    memoryRefresh: {
      idea: "Numeros negativos sao numeros abaixo de zero. Em uma expressao, faca a multiplicacao primeiro e acompanhe o sinal antes de combinar.",
      method: ["Faca multiplicacao ou divisao antes da adicao.", "Negativo vezes positivo e negativo.", "Negativo vezes negativo e positivo.", "Ao somar um positivo a um negativo, caminhe em direcao ao zero."],
      example: "-6 x 5 + 12 vira -30 + 12, que e -18.",
    },
    rhythm: ["Negativo vezes positivo e negativo.", "Negativo vezes negativo e positivo.", "Confira o sinal antes do tamanho."],
    prompt: "Encontre o valor de -8 x 7 + 18.",
    correction:
      "Primeiro multiplique: -8 x 7 = -56. Depois some 18, andando 18 passos em direcao ao zero.",
  },
  "g7-expression-like-terms": {
    grade: "7o ano",
    block: "Algebra",
    title: "Juntando termos semelhantes",
    sourceFocus: "Algebra do 7o ano: desenvolver forma clara ao simplificar expressoes.",
    teacherAim:
      "Os estudantes separam termos diferentes e constantes, depois simplificam com passos visiveis e organizados.",
    memoryRefresh: {
      idea: "Termos semelhantes tem a mesma parte com letra. Numeros sem letra combinam apenas com numeros sem letra.",
      method: ["Circule ou junte termos com a mesma letra.", "Mantenha o sinal ligado a cada termo.", "Some ou subtraia os coeficientes.", "Escreva os termos diferentes separados em uma expressao limpa."],
      example: "4m - 7 + 2m + 3 vira 6m - 4.",
    },
    rhythm: ["Junte as mesmas letras.", "Junte os numeros sem letra.", "Mantenha termos diferentes separados."],
    prompt: "Simplifique: 6k - 3 + 4k - 11. Escreva a expressao simplificada.",
    correction:
      "Junte 6k e 4k para formar 10k. Junte -3 e -11 para formar -14.",
  },
  "g7-equation-balance": {
    grade: "7o ano",
    block: "Algebra",
    title: "Equilibre a equacao",
    sourceFocus: "Algebra do 7o ano: resolver equacoes fazendo a mesma coisa nos dois lados.",
    teacherAim:
      "Os estudantes usam a regra de ouro das equacoes e verificam o valor por substituicao.",
    memoryRefresh: {
      idea: "Uma equacao e um desafio de equilibrio. Tudo que voce faz em um lado tambem deve fazer no outro.",
      method: ["Leve os termos com variavel para um lado fazendo a mesma operacao nos dois lados.", "Leve os numeros sem letra para o outro lado.", "Divida pelo numero que multiplica a variavel.", "Confira substituindo a resposta na equacao original."],
      example: "2x + 3 = 11. Subtraia 3 dos dois lados: 2x = 8. Divida os dois lados por 2: x = 4.",
    },
    rhythm: ["Mantenha o sinal de igual equilibrado.", "Reuna as constantes.", "Divida por ultimo."],
    prompt: "Resolva para x: 5x - 2 = 3x + 8.",
    correction:
      "Subtraia 3x dos dois lados para obter 2x - 2 = 8. Some 2 nos dois lados, depois divida por 2.",
  },
  "g7-gauss-sum": {
    grade: "7o ano",
    block: "Formulas",
    title: "A soma de Gauss",
    sourceFocus: "Formulas do 7o ano: usar primeiro termo, ultimo termo e numero de termos para somar uma sequencia aritmetica.",
    teacherAim:
      "Os estudantes vivenciam uma formula como pensamento condensado, nao apenas como regra para decorar.",
    memoryRefresh: {
      idea: "Uma formula pode guardar um padrao de forma curta. Em uma sequencia regular, faca pares com o primeiro e o ultimo numero.",
      method: ["Encontre o primeiro e o ultimo numero.", "Conte quantos numeros ha na sequencia.", "Some primeiro mais ultimo.", "Multiplique pela quantidade de termos e divida por 2."],
      example: "Para 2 + 4 + 6 + 8, primeiro mais ultimo e 10, ha 4 numeros, entao 4 x 10 dividido por 2 = 20.",
    },
    rhythm: ["Faca pares do primeiro com o ultimo.", "Conte quantos numeros existem.", "Use metade da quantidade vezes a soma do par."],
    prompt: "Encontre a soma de 12 + 15 + 18 + ... + 48.",
    correction:
      "A sequencia tem 13 numeros. Primeiro mais ultimo e 60. Use 13 x 60 / 2.",
  },
  "g7-table-square-products": {
    grade: "7o ano",
    block: "Revisao aritmetica",
    title: "Pensamento da tabuada",
    sourceFocus: "Fluencia na tabuada a partir do modelo de 1 a 12.",
    teacherAim:
      "Os estudantes reconstruem um fato de multiplicacao por duplicacao e simetria, em vez de adivinhar.",
    memoryRefresh: {
      idea: "Quando uma tabuada esta enferrujada, construa a resposta a partir de um fato proximo que voce conhece bem.",
      method: ["Escolha um fato relacionado mais facil.", "Dobre, divida pela metade ou some outro grupo ate chegar ao fato desejado.", "Use a multiplicacao invertida para conferir.", "Escreva o produto final apenas depois que a verificacao fizer sentido."],
      example: "Para 7 x 8, use 7 x 4 = 28 e depois dobre 28 para obter 56.",
    },
    examplePt:
      "Exemplo: para 6 x 8, pense 6 x 4 = 24. Dobrar 24 da 48, entao 6 x 8 = 48. Tambem podemos verificar: 8 x 6 = 48.",
    rhythm: ["Use um fato que voce conhece.", "Dobre ou divida pela metade quando ajudar.", "Confira trocando a ordem dos fatores."],
    prompt: "Complete os passos para 7 x 8. Depois de o produto final.",
    guidedSteps: [
      { label: "Passo 1: Calcule 7 x 4.", answerType: "number", answer: 28 },
      { label: "Passo 2: Dobre o resultado para chegar a 7 x 8.", answerType: "number", answer: 56 },
      { label: "Passo 3: Verifique: 8 x 7 =", answerType: "number", answer: 56 },
    ],
    correction: "Respostas corretas: 7 x 4 = 28; dobrando 28 obtemos 56; 8 x 7 tambem e 56.",
  },
  "g7-missing-digit": {
    grade: "7o ano",
    block: "Desafios",
    title: "Multiplicacao com algarismo faltando",
    sourceFocus: "Desafios de multiplicacao com algarismo faltando e aritmetica de algarismos.",
    teacherAim:
      "Os estudantes raciocinam com valor posicional, transporte e fatos de multiplicacao antes de nomear o algarismo faltante.",
    memoryRefresh: {
      idea: "Multiplicacao com algarismo faltando se resolve coluna por coluna. A coluna das unidades costuma dar a primeira pista.",
      method: ["Observe o algarismo das unidades da resposta.", "Descubra qual algarismo poderia produzir essa unidade.", "Inclua o transporte na coluna das dezenas.", "Confira a multiplicacao completa."],
      example: "Em 2? x 3 = 78, a unidade precisa fazer 3 x ? terminar em 8, entao ? e 6. Depois, 26 x 3 = 78.",
    },
    examplePt:
      "Exemplo: em 3? x 4 = 148, olhe primeiro para as unidades. 4 x ? termina em 8, entao ? pode ser 2 ou 7. Testando 37 x 4 = 148, o algarismo faltante e 7.",
    rhythm: ["Comece pela coluna das unidades.", "Use o transporte.", "Confira a multiplicacao inteira."],
    prompt: "Encontre o algarismo faltante em 4? x 6 = 276. Depois escreva o numero completo de dois algarismos.",
    guidedSteps: [
      { label: "Passo 1: Qual algarismo faz 6 x ? terminar em 6?", answerType: "number", answer: 6 },
      { label: "Passo 2: 6 x 6 = 36; qual transporte vai para a dezena?", answerType: "number", answer: 3 },
      { label: "Passo 3: Confira as dezenas: 6 x 4 + 3 =", answerType: "number", answer: 27 },
    ],
    correction: "Respostas corretas: o algarismo e 6; o transporte e 3; 6 x 4 + 3 = 27; o numero completo e 46.",
  },
  "g7-fraction-common-denominator": {
    grade: "7o ano",
    block: "Fracoes",
    title: "Soma com denominador comum",
    sourceFocus: "Soma de fracoes e revisao de fracoes-decimais.",
    teacherAim:
      "Os estudantes mostram a escolha do denominador, fracoes equivalentes e o resultado final como numero misto.",
    memoryRefresh: {
      idea: "Fracoes so podem ser somadas diretamente quando os pedacos tem o mesmo tamanho. Um denominador comum faz os pedacos ficarem iguais.",
      method: ["Escolha um denominador comum.", "Reescreva cada fracao sem mudar seu valor.", "Some os numeradores e mantenha o denominador.", "Reduza ou escreva um numero misto se necessario."],
      example: "1/3 + 1/6 vira 2/6 + 1/6 = 3/6 = 1/2.",
    },
    examplePt:
      "Exemplo: para 1/3 + 1/4, use denominador 12. Entao 1/3 = 4/12 e 1/4 = 3/12. Somando: 7/12.",
    rhythm: ["Escolha um denominador comum.", "Reescreva as duas fracoes.", "Some os numeradores e mantenha o denominador."],
    prompt: "Some 5/6 + 3/8. Complete cada passo antes da resposta final.",
    guidedSteps: [
      { label: "Passo 1: Escolha um denominador comum.", answerType: "number", answer: 24 },
      { label: "Passo 2: Reescreva 5/6 em vinte e quatro avos.", answerType: "expression", acceptedAnswers: ["20/24"] },
      { label: "Passo 3: Reescreva 3/8 em vinte e quatro avos.", answerType: "expression", acceptedAnswers: ["9/24"] },
      { label: "Passo 4: Some os numeradores.", answerType: "expression", acceptedAnswers: ["29/24"] },
    ],
    correction: "Respostas corretas: denominador comum 24; 5/6 = 20/24; 3/8 = 9/24; soma = 29/24 = 1 5/24.",
  },
  "g7-decimal-division-shift": {
    grade: "7o ano",
    block: "Decimais",
    title: "Transforme o divisor em inteiro",
    sourceFocus: "Revisao de divisao decimal: ajustar o divisor movendo as virgulas antes de dividir.",
    teacherAim:
      "Os estudantes transformam um problema de divisao equivalente e estimam antes de calcular.",
    memoryRefresh: {
      idea: "Divisao com decimais fica mais facil quando o divisor e um numero inteiro. Mova as duas virgulas o mesmo numero de casas para manter a divisao equivalente.",
      method: ["Conte quantas casas movem o divisor ate virar inteiro.", "Mova o dividendo o mesmo numero de casas.", "Divida os novos numeros.", "Estime antes para perceber erro de virgula."],
      example: "4.8 dividido por 0.6 vira 48 dividido por 6, entao a resposta e 8.",
    },
    examplePt:
      "Exemplo: 36 dividido por 0.09 fica 3600 dividido por 9, porque movemos as duas virgulas duas casas para a direita. A resposta e 400.",
    rhythm: ["Mova as duas virgulas o mesmo numero de casas.", "Transforme o divisor em inteiro.", "Estime antes de dividir."],
    prompt: "Resolva 21.3 dividido por 5.68. Arredonde para o centesimo mais proximo.",
    guidedSteps: [
      { label: "Passo 1: Mova as virgulas quantas casas?", answerType: "number", answer: 2 },
      { label: "Passo 2: O problema equivalente e 2130 dividido por", answerType: "number", answer: 568 },
      { label: "Passo 3: Estime a resposta para o inteiro mais proximo.", answerType: "number", answer: 4, tolerance: 1 },
    ],
    correction: "Respostas corretas: mova 2 casas; 21.3 dividido por 5.68 = 2130 dividido por 568; o resultado e aproximadamente 3.75.",
  },
  "g7-unit-cost": {
    grade: "7o ano",
    block: "Custo unitario",
    title: "Qual preco e melhor?",
    sourceFocus: "Problemas de custo unitario das folhas de revisao aritmetica.",
    teacherAim:
      "Os estudantes dividem o custo total pela quantidade e comparam precos de uma unidade.",
    memoryRefresh: {
      idea: "Custo unitario significa o preco de um item. Depois que as escolhas viram preco de um item, a comparacao fica justa.",
      method: ["Divida o preco total pela quantidade de itens.", "Faca isso para cada loja ou opcao.", "Compare a mesma unidade nas duas respostas.", "Escolha o menor preco unitario como melhor compra."],
      example: "Se 4 cadernos custam $10, um caderno custa $10 dividido por 4 = $2.50.",
    },
    examplePt:
      "Exemplo: se 5 laranjas custam R$10,00, cada laranja custa R$2,00, porque 10 dividido por 5 = 2.",
    rhythm: ["Encontre o preco de um item.", "Compare unidades iguais.", "Escolha o menor preco unitario."],
    prompt: "A loja A vende 6 lapis por $4.20. A loja B vende 10 lapis por $6.50. Qual loja e mais barata por lapis?",
    guidedSteps: [
      { label: "Passo 1: Preco unitario da loja A: 4.20 dividido por 6 =", answerType: "number", answer: 0.7, tolerance: 0.001 },
      { label: "Passo 2: Preco unitario da loja B: 6.50 dividido por 10 =", answerType: "number", answer: 0.65, tolerance: 0.001 },
      { label: "Passo 3: Qual preco unitario e menor, A ou B?", answerType: "expression", acceptedAnswers: ["b", "storeb", "store b"] },
    ],
    correction: "Respostas corretas: Loja A = $0.70 por lapis; Loja B = $0.65 por lapis; a Loja B e mais barata.",
  },
  "g7-divisibility-check": {
    grade: "7o ano",
    block: "Divisibilidade",
    title: "Regras de divisibilidade",
    sourceFocus: "Divisibilidade por 2, 3, 4, 5, 9 e 10.",
    teacherAim:
      "Os estudantes usam testes com algarismos e explicam quais divisores funcionam.",
    memoryRefresh: {
      idea: "Regras de divisibilidade sao verificacoes rapidas que usam algarismos em vez de divisao longa.",
      method: ["Confira 2 pelo ultimo algarismo.", "Confira 3 e 9 somando os algarismos.", "Confira 4 pelos dois ultimos algarismos.", "Confira 5 e 10 pelo algarismo final."],
      example: "732 e divisivel por 2 porque e par, por 3 porque 7 + 3 + 2 = 12, e por 4 porque 32 e divisivel por 4.",
    },
    examplePt:
      "Exemplo: 732 e divisivel por 3 porque 7 + 3 + 2 = 12, e 12 e divisivel por 3. Nao e divisivel por 5 porque nao termina em 0 ou 5.",
    rhythm: ["Confira o ultimo algarismo.", "Some os algarismos.", "Confira os dois ultimos algarismos para 4."],
    prompt: "Quais numeros entre 2, 3, 4, 5, 9 e 10 dividem 85.734 exatamente?",
    guidedSteps: [
      { label: "Passo 1: Some os algarismos: 8 + 5 + 7 + 3 + 4 =", answerType: "number", answer: 27 },
      { label: "Passo 2: O numero e par? Responda sim ou nao.", answerType: "expression", acceptedAnswers: ["yes", "sim"] },
      { label: "Passo 3: Os dois ultimos algarismos, 34, sao divisiveis por 4? Responda sim ou nao.", answerType: "expression", acceptedAnswers: ["no", "nao", "não"] },
    ],
    correction: "Respostas corretas: soma dos algarismos = 27; o numero e par; 34 nao e divisivel por 4. Divisores: 2, 3 e 9.",
  },
  "g7-reduce-fraction": {
    grade: "7o ano",
    block: "Fracoes",
    title: "Reduza uma fracao grande",
    sourceFocus: "Reducao de fracoes grandes na revisao aritmetica do 7o ano.",
    teacherAim:
      "Os estudantes reduzem em etapas visiveis em vez de tentar saltar direto para a resposta.",
    memoryRefresh: {
      idea: "Reduzir uma fracao significa dividir numerador e denominador pelo mesmo fator, mantendo o valor igual.",
      method: ["Procure um fator comum facil.", "Divida em cima e embaixo por esse fator.", "Repita ate nao haver fator comum.", "Confira se numerador e denominador continuam inteiros."],
      example: "48/60 pode ser dividido por 12 para obter 4/5.",
    },
    examplePt:
      "Exemplo: 36/48 pode ser dividido por 12. Entao 36 dividido por 12 = 3 e 48 dividido por 12 = 4, logo 36/48 = 3/4.",
    rhythm: ["Encontre um fator comum.", "Divida numerador e denominador pelo mesmo numero.", "Continue reduzindo ate nao haver fator comum."],
    prompt: "Reduza 7560/8100 aos menores termos.",
    guidedSteps: [
      { label: "Passo 1: Divida numerador e denominador por 180. Novo numerador:", answerType: "number", answer: 42 },
      { label: "Passo 2: Divida numerador e denominador por 180. Novo denominador:", answerType: "number", answer: 45 },
      { label: "Passo 3: Reduza 42/45 por 3.", answerType: "expression", acceptedAnswers: ["14/15"] },
    ],
    correction: "Respostas corretas: 7560/8100 dividido por 180 = 42/45; depois 42/45 dividido por 3 = 14/15.",
  },
  "g7-repeating-decimal-fraction": {
    grade: "7o ano",
    block: "Dizimas periodicas",
    title: "Dizima periodica para fracao",
    sourceFocus: "Conversao de dizimas periodicas em fracoes.",
    teacherAim:
      "Os estudantes conectam um bloco repetido aos 9 no denominador e depois reduzem.",
    memoryRefresh: {
      idea: "Uma dizima periodica pode muitas vezes virar uma fracao com 9 no denominador. A quantidade de algarismos que repetem diz quantos 9 usar.",
      method: ["Conte os algarismos que repetem.", "Coloque o bloco que repete sobre a mesma quantidade de 9.", "Reduza a fracao.", "Confira se o decimal repetiria o mesmo bloco."],
      example: "0.45 repetindo tem dois algarismos repetidos, entao vira 45/99, que reduz para 5/11.",
    },
    examplePt:
      "Exemplo: 0.27 repetindo vira 27/99, porque dois algarismos repetem. Depois reduzimos: 27/99 = 3/11.",
    rhythm: ["Conte os algarismos que repetem.", "Use o mesmo numero de 9 no denominador.", "Reduza a fracao."],
    prompt: "Converta 0.36 repetindo em uma fracao nos menores termos.",
    guidedSteps: [
      { label: "Passo 1: Quantos algarismos repetem?", answerType: "number", answer: 2 },
      { label: "Passo 2: Escreva a primeira fracao antes de reduzir.", answerType: "expression", acceptedAnswers: ["36/99"] },
      { label: "Passo 3: Divida numerador e denominador por 9.", answerType: "expression", acceptedAnswers: ["4/11"] },
    ],
    correction: "Respostas corretas: dois algarismos repetem; 0.363636... = 36/99; reduzindo por 9 obtemos 4/11.",
  },
};

const lessonWorkedSteps = {
  pt: {
    "g7-percent-base": [
      "Modelo para relembrar: 18 dividido por 0.30 pergunta: 18 e 30% de qual todo?",
      "30% = 30/100 = 3/10. Entao 18 representa 3 partes de 10.",
      "Se 3 partes valem 18, entao 1 parte vale 18 dividido por 3 = 6.",
      "Se 1/10 vale 6, entao 10/10 vale 6 x 10 = 60. Confira: 30% de 60 e 18.",
      "Agora faca a atividade: 42 e 35% de qual todo?",
      "35% = 35/100. Se 35 partes valem 42, entao 1 parte vale 42 dividido por 35 = 1.2.",
      "Reconstrua 100 partes: 1.2 x 100 = 120. Confira: 35% de 120 e 42.",
    ],
    "g7-compound-interest": [
      "Comece com o dinheiro inicial: 200 dolares.",
      "Ano 1: 5% de 200 e 0.05 x 200 = 10.",
      "Some os juros ao saldo: 200 + 10 = 210.",
      "Ano 2: agora os juros sao sobre 210. Entao 5% de 210 e 0.05 x 210 = 10.50.",
      "Some novamente: 210 + 10.50 = 220.50.",
    ],
    "g7-ratio-whole": [
      "A razao 2:3 tem 2 partes vermelhas e 3 partes amarelas.",
      "Some as partes: 2 + 3 = 5 partes ao todo.",
      "As flores amarelas sao 3 dessas 5 partes, ou seja, 3/5 do total.",
      "Calcule 3/5 de 45: primeiro 45 dividido por 5 = 9.",
      "Agora tome 3 partes: 9 x 3 = 27 flores amarelas.",
    ],
    "g7-rate-speed": [
      "A pergunta pede milhas por hora, entao precisamos saber quanto seria em 1 hora.",
      "Transforme 15 minutos em horas: 15 minutos e 1/4 de hora.",
      "O ciclista faz 6 milhas em 1/4 de hora.",
      "Para chegar a 1 hora, multiplicamos o tempo por 4.",
      "Fazemos o mesmo com a distancia: 6 x 4 = 24 milhas em 1 hora.",
    ],
    "g7-negative-numbers": [
      "Comece pela multiplicacao, porque ela vem antes da adicao.",
      "-8 x 7 significa 8 grupos negativos de 7, entao o resultado e -56.",
      "Agora a expressao ficou -56 + 18.",
      "Somar 18 a -56 move 18 passos em direcao ao zero.",
      "-56 + 18 = -38.",
    ],
    "g7-expression-like-terms": [
      "Escreva a expressao mantendo cada sinal: 6k - 3 + 4k - 11.",
      "Junte os termos com k: 6k + 4k = 10k.",
      "Junte os numeros sem letra: -3 - 11 = -14.",
      "Agora escreva as duas partes juntas: 10k - 14.",
      "Confira: nao podemos juntar 10k com -14, porque um tem letra e o outro nao.",
    ],
    "g7-equation-balance": [
      "Comece com 5x - 2 = 3x + 8.",
      "Tire 3x dos dois lados para reunir os x: 5x - 3x - 2 = 8.",
      "Isso vira 2x - 2 = 8.",
      "Some 2 nos dois lados: 2x = 10.",
      "Divida os dois lados por 2: x = 5. Confira: 5(5) - 2 = 23 e 3(5) + 8 = 23.",
    ],
    "g7-gauss-sum": [
      "A sequencia e 12, 15, 18, ..., 48. Ela cresce de 3 em 3.",
      "Conte os termos: 12 ate 48 de 3 em 3 da 13 numeros.",
      "Faca pares do primeiro com o ultimo: 12 + 48 = 60.",
      "Cada par semelhante soma 60.",
      "Use metade da quantidade de termos vezes a soma do par: 13 x 60 dividido por 2 = 390.",
    ],
    "g7-table-square-products": [
      "Se 7 x 8 ainda nao esta fresco, use uma tabuada mais facil.",
      "Metade de 8 e 4, entao calcule 7 x 4 primeiro.",
      "7 x 4 = 28.",
      "Como 8 e o dobro de 4, dobre tambem o resultado: 28 x 2 = 56.",
      "Confira pela ordem inversa: 8 x 7 tambem deve dar 56.",
    ],
    "g7-missing-digit": [
      "Olhe para as unidades em 4? x 6 = 276.",
      "A resposta termina em 6, entao precisamos de 6 x ? terminando em 6.",
      "6 x 6 = 36, entao o algarismo faltante pode ser 6 e vai 3 para a dezena.",
      "Confira as dezenas: 6 x 4 = 24, e 24 + 3 = 27.",
      "A resposta completa fica 46 x 6 = 276.",
    ],
    "g7-fraction-common-denominator": [
      "Para somar 5/6 + 3/8, os denominadores precisam ficar iguais.",
      "Um denominador comum para 6 e 8 e 24.",
      "Transforme 5/6 em vinte e quatro avos: 6 x 4 = 24, entao 5 x 4 = 20. Fica 20/24.",
      "Transforme 3/8 em vinte e quatro avos: 8 x 3 = 24, entao 3 x 3 = 9. Fica 9/24.",
      "Some: 20/24 + 9/24 = 29/24, que tambem e 1 5/24.",
    ],
    "g7-decimal-division-shift": [
      "A conta e 21.3 dividido por 5.68. O divisor 5.68 tem duas casas decimais.",
      "Mova a virgula do divisor duas casas para a direita: 5.68 vira 568.",
      "Mova a virgula do dividendo tambem duas casas para a direita: 21.3 vira 2130.",
      "Agora resolva a conta equivalente: 2130 dividido por 568.",
      "O resultado e aproximadamente 3.75. Confira por estimativa: 568 x 4 e 2272, um pouco maior que 2130, entao 3.75 faz sentido.",
    ],
    "g7-unit-cost": [
      "Para comparar, descubra primeiro o preco de 1 lapis em cada loja.",
      "Loja A: 4.20 dividido por 6 = 0.70 por lapis.",
      "Loja B: 6.50 dividido por 10 = 0.65 por lapis.",
      "Agora compare unidades iguais: 0.70 por lapis contra 0.65 por lapis.",
      "0.65 e menor que 0.70, entao a Loja B e mais barata.",
    ],
    "g7-divisibility-check": [
      "Confira por 2: 85.734 termina em 4, entao e par e divisivel por 2.",
      "Confira por 3: some os algarismos 8 + 5 + 7 + 3 + 4 = 27. Como 27 e divisivel por 3, o numero tambem e.",
      "Confira por 4: olhe os dois ultimos algarismos, 34. Como 34 nao e divisivel por 4, o numero nao e.",
      "Confira por 5 e 10: o numero nao termina em 0 ou 5, entao nao serve.",
      "Confira por 9: a soma dos algarismos e 27, e 27 e divisivel por 9. Resposta: 2, 3 e 9.",
    ],
    "g7-reduce-fraction": [
      "Comece com 7560/8100.",
      "Procure um fator comum grande. Os dois podem ser divididos por 180.",
      "7560 dividido por 180 = 42, e 8100 dividido por 180 = 45. Fica 42/45.",
      "Ainda da para dividir por 3: 42 dividido por 3 = 14, e 45 dividido por 3 = 15.",
      "A fracao reduzida e 14/15.",
    ],
    "g7-repeating-decimal-fraction": [
      "O decimal 0.36 repetindo significa 0.363636...",
      "O bloco que repete tem dois algarismos: 36.",
      "Dois algarismos repetindo usam dois 9 no denominador: 36/99.",
      "Reduza a fracao dividindo por 9: 36 dividido por 9 = 4, e 99 dividido por 9 = 11.",
      "Entao 0.36 repetindo = 4/11.",
    ],
  },
  en: {
    "g7-percent-base": [
      "Memory model: 18 divided by 0.30 asks: 18 is 30% of what whole?",
      "30% = 30/100 = 3/10. So 18 represents 3 parts out of 10.",
      "If 3 parts are worth 18, then 1 part is 18 divided by 3 = 6.",
      "If 1/10 is 6, then 10/10 is 6 x 10 = 60. Check: 30% of 60 is 18.",
      "Now do the activity: 42 is 35% of what whole?",
      "35% = 35/100. If 35 parts are worth 42, then 1 part is 42 divided by 35 = 1.2.",
      "Rebuild 100 parts: 1.2 x 100 = 120. Check: 35% of 120 is 42.",
    ],
    "g7-compound-interest": [
      "Start with the principal: 200 dollars.",
      "Year 1: 5% of 200 is 0.05 x 200 = 10.",
      "Add the interest to the balance: 200 + 10 = 210.",
      "Year 2: the interest is now based on 210. So 5% of 210 is 0.05 x 210 = 10.50.",
      "Add again: 210 + 10.50 = 220.50.",
    ],
    "g7-ratio-whole": [
      "The ratio 2:3 means 2 red parts and 3 yellow parts.",
      "Add the parts: 2 + 3 = 5 total parts.",
      "Yellow flowers are 3 of those 5 parts, or 3/5 of the total.",
      "Find 3/5 of 45: first 45 divided by 5 = 9.",
      "Now take 3 parts: 9 x 3 = 27 yellow flowers.",
    ],
    "g7-rate-speed": [
      "The question asks for miles per hour, so we need the distance in 1 hour.",
      "Change 15 minutes into hours: 15 minutes is 1/4 hour.",
      "The cyclist goes 6 miles in 1/4 hour.",
      "To reach 1 hour, multiply the time by 4.",
      "Do the same to the distance: 6 x 4 = 24 miles in 1 hour.",
    ],
    "g7-negative-numbers": [
      "Start with multiplication, because it comes before addition.",
      "-8 x 7 means 8 negative groups of 7, so the result is -56.",
      "Now the expression is -56 + 18.",
      "Adding 18 to -56 moves 18 steps toward zero.",
      "-56 + 18 = -38.",
    ],
    "g7-expression-like-terms": [
      "Write the expression while keeping every sign: 6k - 3 + 4k - 11.",
      "Combine the k terms: 6k + 4k = 10k.",
      "Combine the plain numbers: -3 - 11 = -14.",
      "Now write both parts together: 10k - 14.",
      "Check: 10k and -14 cannot combine because one has a letter and one does not.",
    ],
    "g7-equation-balance": [
      "Start with 5x - 2 = 3x + 8.",
      "Subtract 3x from both sides to gather the x terms: 5x - 3x - 2 = 8.",
      "That becomes 2x - 2 = 8.",
      "Add 2 to both sides: 2x = 10.",
      "Divide both sides by 2: x = 5. Check: 5(5) - 2 = 23 and 3(5) + 8 = 23.",
    ],
    "g7-gauss-sum": [
      "The sequence is 12, 15, 18, ..., 48. It grows by 3 each time.",
      "Count the terms: 12 to 48 by 3s gives 13 numbers.",
      "Pair the first and last: 12 + 48 = 60.",
      "Each matching pair has the same sum, 60.",
      "Use half the number of terms times the pair sum: 13 x 60 divided by 2 = 390.",
    ],
    "g7-table-square-products": [
      "If 7 x 8 is not fresh, use an easier fact.",
      "Half of 8 is 4, so calculate 7 x 4 first.",
      "7 x 4 = 28.",
      "Since 8 is double 4, double the result too: 28 x 2 = 56.",
      "Check with the turn-around fact: 8 x 7 should also be 56.",
    ],
    "g7-missing-digit": [
      "Look at the ones column in 4? x 6 = 276.",
      "The answer ends in 6, so we need 6 x ? to end in 6.",
      "6 x 6 = 36, so the missing digit can be 6 and the carry is 3.",
      "Check the tens: 6 x 4 = 24, and 24 + 3 = 27.",
      "The full multiplication is 46 x 6 = 276.",
    ],
    "g7-fraction-common-denominator": [
      "To add 5/6 + 3/8, the denominators need to match.",
      "A common denominator for 6 and 8 is 24.",
      "Change 5/6 to twenty-fourths: 6 x 4 = 24, so 5 x 4 = 20. It becomes 20/24.",
      "Change 3/8 to twenty-fourths: 8 x 3 = 24, so 3 x 3 = 9. It becomes 9/24.",
      "Add: 20/24 + 9/24 = 29/24, which is also 1 5/24.",
    ],
    "g7-decimal-division-shift": [
      "The problem is 21.3 divided by 5.68. The divisor 5.68 has two decimal places.",
      "Move the divisor decimal two places to the right: 5.68 becomes 568.",
      "Move the dividend decimal two places to the right too: 21.3 becomes 2130.",
      "Now solve the equivalent problem: 2130 divided by 568.",
      "The result is about 3.75. Estimate check: 568 x 4 is 2272, a little too high, so 3.75 makes sense.",
    ],
    "g7-unit-cost": [
      "To compare, first find the price of 1 pencil at each store.",
      "Store A: 4.20 divided by 6 = 0.70 per pencil.",
      "Store B: 6.50 divided by 10 = 0.65 per pencil.",
      "Now compare equal units: 0.70 per pencil versus 0.65 per pencil.",
      "0.65 is less than 0.70, so Store B is cheaper.",
    ],
    "g7-divisibility-check": [
      "Check 2: 85,734 ends in 4, so it is even and divisible by 2.",
      "Check 3: add the digits 8 + 5 + 7 + 3 + 4 = 27. Since 27 is divisible by 3, the number is too.",
      "Check 4: look at the last two digits, 34. Since 34 is not divisible by 4, the number is not.",
      "Check 5 and 10: the number does not end in 0 or 5, so those do not work.",
      "Check 9: the digit sum is 27, and 27 is divisible by 9. Answer: 2, 3, and 9.",
    ],
    "g7-reduce-fraction": [
      "Start with 7560/8100.",
      "Look for a large common factor. Both numbers can be divided by 180.",
      "7560 divided by 180 = 42, and 8100 divided by 180 = 45. Now we have 42/45.",
      "We can still divide by 3: 42 divided by 3 = 14, and 45 divided by 3 = 15.",
      "The reduced fraction is 14/15.",
    ],
    "g7-repeating-decimal-fraction": [
      "The decimal 0.36 repeating means 0.363636...",
      "The repeating block has two digits: 36.",
      "Two repeating digits use two 9s in the denominator: 36/99.",
      "Reduce by dividing by 9: 36 divided by 9 = 4, and 99 divided by 9 = 11.",
      "So 0.36 repeating = 4/11.",
    ],
  },
};

const extraPracticeBank = {
  pt: {
    "g7-percent-base": {
      prompt: "Treino: 24 e 40% de qual numero?",
      answerType: "number",
      answer: 60,
      tolerance: 0,
      steps: ["40% = 40/100 = 4/10.", "Se 4 partes valem 24, 1 parte vale 24 dividido por 4 = 6.", "O todo tem 10 partes, entao 6 x 10 = 60.", "Confira: 40% de 60 e 24."],
    },
    "g7-compound-interest": {
      prompt: "Treino: 300 dolares rendem 4% ao ano, compostos anualmente. Qual e o saldo depois de 2 anos?",
      answerType: "number",
      answer: 324.48,
      tolerance: 0.01,
      steps: ["Ano 1: 4% de 300 = 12.", "Novo saldo: 300 + 12 = 312.", "Ano 2: 4% de 312 = 12.48.", "Saldo final: 312 + 12.48 = 324.48."],
    },
    "g7-ratio-whole": {
      prompt: "Treino: Uma receita usa farinha e aveia na razao 3:2. Ha 40 xicaras ao todo. Quantas xicaras sao de farinha?",
      answerType: "number",
      answer: 24,
      tolerance: 0,
      steps: ["Some as partes: 3 + 2 = 5.", "Farinha e 3 das 5 partes.", "40 dividido por 5 = 8.", "3 partes de farinha: 3 x 8 = 24."],
    },
    "g7-rate-speed": {
      prompt: "Treino: Uma pessoa caminha 9 km em 30 minutos. Qual e a velocidade media em km por hora?",
      answerType: "number",
      answer: 18,
      tolerance: 0,
      steps: ["30 minutos e 1/2 hora.", "Se 9 km acontecem em meia hora, em 1 hora sera o dobro.", "9 x 2 = 18.", "Velocidade media: 18 km/h."],
    },
    "g7-negative-numbers": {
      prompt: "Treino: Calcule -6 x 9 + 20.",
      answerType: "number",
      answer: -34,
      tolerance: 0,
      steps: ["Faca a multiplicacao primeiro.", "-6 x 9 = -54.", "Agora some 20: -54 + 20.", "Andando 20 passos em direcao ao zero, chegamos a -34."],
    },
    "g7-expression-like-terms": {
      prompt: "Treino: Simplifique 8m - 5 + 3m - 12.",
      answerType: "expression",
      acceptedAnswers: ["11m-17", "11m - 17"],
      steps: ["Junte os termos com m: 8m + 3m = 11m.", "Junte os numeros: -5 - 12 = -17.", "Escreva a expressao final: 11m - 17."],
    },
    "g7-equation-balance": {
      prompt: "Treino: Resolva para x: 4x + 6 = 2x + 18.",
      answerType: "number",
      answer: 6,
      tolerance: 0,
      steps: ["Subtraia 2x dos dois lados: 2x + 6 = 18.", "Subtraia 6 dos dois lados: 2x = 12.", "Divida por 2: x = 6.", "Confira: 4(6)+6 = 30 e 2(6)+18 = 30."],
    },
    "g7-gauss-sum": {
      prompt: "Treino: Some 5 + 8 + 11 + ... + 35.",
      answerType: "number",
      answer: 220,
      tolerance: 0,
      steps: ["A sequencia cresce de 3 em 3.", "De 5 ate 35 ha 11 termos.", "Primeiro + ultimo: 5 + 35 = 40.", "Soma: 11 x 40 dividido por 2 = 220."],
    },
    "g7-table-square-products": {
      prompt: "Treino: Use um fato conhecido para calcular 9 x 6.",
      answerType: "number",
      answer: 54,
      tolerance: 0,
      steps: ["Use 9 x 3 = 27.", "Como 6 e o dobro de 3, dobre o resultado.", "27 x 2 = 54.", "Confira: 6 x 9 tambem e 54."],
    },
    "g7-missing-digit": {
      prompt: "Treino: Encontre o numero completo em 3? x 4 = 156.",
      answerType: "number",
      answer: 39,
      tolerance: 0,
      steps: ["Olhe as unidades: a resposta termina em 6.", "4 x ? precisa terminar em 6. 4 x 9 = 36.", "Vai 3 para a dezena.", "4 x 3 + 3 = 15. Entao o numero e 39."],
    },
    "g7-fraction-common-denominator": {
      prompt: "Treino: Some 2/3 + 5/12.",
      answerType: "expression",
      acceptedAnswers: ["13/12", "1 1/12", "1+1/12"],
      steps: ["Use denominador comum 12.", "2/3 = 8/12.", "5/12 ja esta em doze avos.", "8/12 + 5/12 = 13/12 = 1 1/12."],
    },
    "g7-decimal-division-shift": {
      prompt: "Treino: Resolva 14.4 dividido por 0.36.",
      answerType: "number",
      answer: 40,
      tolerance: 0,
      steps: ["O divisor 0.36 tem duas casas decimais.", "Mova as duas virgulas duas casas: 14.4 vira 1440 e 0.36 vira 36.", "Resolva 1440 dividido por 36.", "36 x 40 = 1440, entao a resposta e 40."],
    },
    "g7-unit-cost": {
      prompt: "Treino: Loja A vende 8 canetas por $5.60. Loja B vende 5 canetas por $3.75. Qual loja e mais barata por caneta?",
      answerType: "expression",
      acceptedAnswers: ["a", "lojaa", "loja a"],
      steps: ["Loja A: 5.60 dividido por 8 = 0.70.", "Loja B: 3.75 dividido por 5 = 0.75.", "0.70 e menor que 0.75.", "A Loja A e mais barata por caneta."],
    },
    "g7-divisibility-check": {
      prompt: "Treino: Quais de 2, 3, 4, 5, 9 e 10 dividem 64.512 exatamente?",
      answerType: "expression",
      acceptedAnswers: ["2,3,4,9", "2 3 4 9", "2;3;4;9"],
      steps: ["Termina em 2, entao e divisivel por 2.", "Soma dos algarismos: 6+4+5+1+2 = 18, entao e divisivel por 3 e 9.", "Os dois ultimos algarismos sao 12, entao e divisivel por 4.", "Nao termina em 0 ou 5, entao nao e divisivel por 5 ou 10.", "Resposta: 2, 3, 4 e 9."],
    },
    "g7-reduce-fraction": {
      prompt: "Treino: Reduza 1260/1470.",
      answerType: "expression",
      acceptedAnswers: ["6/7"],
      steps: ["Divida os dois por 210.", "1260 dividido por 210 = 6.", "1470 dividido por 210 = 7.", "A fracao reduzida e 6/7."],
    },
    "g7-repeating-decimal-fraction": {
      prompt: "Treino: Converta 0.72 repetindo em fracao reduzida.",
      answerType: "expression",
      acceptedAnswers: ["8/11"],
      steps: ["O bloco que repete e 72, com dois algarismos.", "Coloque 72 sobre 99: 72/99.", "Reduza dividindo por 9.", "72/99 = 8/11."],
    },
  },
  en: {
    "g7-percent-base": {
      prompt: "Practice: 24 is 40% of what number?",
      answerType: "number",
      answer: 60,
      tolerance: 0,
      steps: ["40% = 40/100 = 4/10.", "If 4 parts are worth 24, 1 part is 24 divided by 4 = 6.", "The whole has 10 parts, so 6 x 10 = 60.", "Check: 40% of 60 is 24."],
    },
    "g7-compound-interest": {
      prompt: "Practice: 300 dollars earns 4% interest compounded annually. What is the balance after 2 years?",
      answerType: "number",
      answer: 324.48,
      tolerance: 0.01,
      steps: ["Year 1: 4% of 300 = 12.", "New balance: 300 + 12 = 312.", "Year 2: 4% of 312 = 12.48.", "Final balance: 312 + 12.48 = 324.48."],
    },
    "g7-ratio-whole": {
      prompt: "Practice: A recipe uses flour and oats in a 3:2 ratio. There are 40 cups altogether. How many cups are flour?",
      answerType: "number",
      answer: 24,
      tolerance: 0,
      steps: ["Add the parts: 3 + 2 = 5.", "Flour is 3 of the 5 parts.", "40 divided by 5 = 8.", "3 flour parts: 3 x 8 = 24."],
    },
    "g7-rate-speed": {
      prompt: "Practice: A person walks 9 km in 30 minutes. What is the average speed in km per hour?",
      answerType: "number",
      answer: 18,
      tolerance: 0,
      steps: ["30 minutes is 1/2 hour.", "If 9 km happens in half an hour, one hour is double.", "9 x 2 = 18.", "Average speed: 18 km/h."],
    },
    "g7-negative-numbers": {
      prompt: "Practice: Calculate -6 x 9 + 20.",
      answerType: "number",
      answer: -34,
      tolerance: 0,
      steps: ["Multiply first.", "-6 x 9 = -54.", "Now add 20: -54 + 20.", "Move 20 steps toward zero to reach -34."],
    },
    "g7-expression-like-terms": {
      prompt: "Practice: Simplify 8m - 5 + 3m - 12.",
      answerType: "expression",
      acceptedAnswers: ["11m-17", "11m - 17"],
      steps: ["Combine m terms: 8m + 3m = 11m.", "Combine plain numbers: -5 - 12 = -17.", "Final expression: 11m - 17."],
    },
    "g7-equation-balance": {
      prompt: "Practice: Solve for x: 4x + 6 = 2x + 18.",
      answerType: "number",
      answer: 6,
      tolerance: 0,
      steps: ["Subtract 2x from both sides: 2x + 6 = 18.", "Subtract 6 from both sides: 2x = 12.", "Divide by 2: x = 6.", "Check: 4(6)+6 = 30 and 2(6)+18 = 30."],
    },
    "g7-gauss-sum": {
      prompt: "Practice: Sum 5 + 8 + 11 + ... + 35.",
      answerType: "number",
      answer: 220,
      tolerance: 0,
      steps: ["The sequence grows by 3.", "From 5 to 35 there are 11 terms.", "First + last: 5 + 35 = 40.", "Sum: 11 x 40 divided by 2 = 220."],
    },
    "g7-table-square-products": {
      prompt: "Practice: Use a known fact to calculate 9 x 6.",
      answerType: "number",
      answer: 54,
      tolerance: 0,
      steps: ["Use 9 x 3 = 27.", "Since 6 is double 3, double the result.", "27 x 2 = 54.", "Check: 6 x 9 is also 54."],
    },
    "g7-missing-digit": {
      prompt: "Practice: Find the complete number in 3? x 4 = 156.",
      answerType: "number",
      answer: 39,
      tolerance: 0,
      steps: ["Look at the ones: the answer ends in 6.", "4 x ? needs to end in 6. 4 x 9 = 36.", "Carry 3 to the tens.", "4 x 3 + 3 = 15. So the number is 39."],
    },
    "g7-fraction-common-denominator": {
      prompt: "Practice: Add 2/3 + 5/12.",
      answerType: "expression",
      acceptedAnswers: ["13/12", "1 1/12", "1+1/12"],
      steps: ["Use common denominator 12.", "2/3 = 8/12.", "5/12 is already in twelfths.", "8/12 + 5/12 = 13/12 = 1 1/12."],
    },
    "g7-decimal-division-shift": {
      prompt: "Practice: Solve 14.4 divided by 0.36.",
      answerType: "number",
      answer: 40,
      tolerance: 0,
      steps: ["The divisor 0.36 has two decimal places.", "Move both decimals two places: 14.4 becomes 1440 and 0.36 becomes 36.", "Solve 1440 divided by 36.", "36 x 40 = 1440, so the answer is 40."],
    },
    "g7-unit-cost": {
      prompt: "Practice: Store A sells 8 pens for $5.60. Store B sells 5 pens for $3.75. Which store is cheaper per pen?",
      answerType: "expression",
      acceptedAnswers: ["a", "storea", "store a"],
      steps: ["Store A: 5.60 divided by 8 = 0.70.", "Store B: 3.75 divided by 5 = 0.75.", "0.70 is less than 0.75.", "Store A is cheaper per pen."],
    },
    "g7-divisibility-check": {
      prompt: "Practice: Which of 2, 3, 4, 5, 9, and 10 divide 64,512 evenly?",
      answerType: "expression",
      acceptedAnswers: ["2,3,4,9", "2 3 4 9", "2;3;4;9"],
      steps: ["It ends in 2, so it is divisible by 2.", "Digit sum: 6+4+5+1+2 = 18, so it is divisible by 3 and 9.", "The last two digits are 12, so it is divisible by 4.", "It does not end in 0 or 5, so not 5 or 10.", "Answer: 2, 3, 4, and 9."],
    },
    "g7-reduce-fraction": {
      prompt: "Practice: Reduce 1260/1470.",
      answerType: "expression",
      acceptedAnswers: ["6/7"],
      steps: ["Divide both numbers by 210.", "1260 divided by 210 = 6.", "1470 divided by 210 = 7.", "The reduced fraction is 6/7."],
    },
    "g7-repeating-decimal-fraction": {
      prompt: "Practice: Convert repeating 0.72 to a reduced fraction.",
      answerType: "expression",
      acceptedAnswers: ["8/11"],
      steps: ["The repeating block is 72, with two digits.", "Put 72 over 99: 72/99.", "Reduce by dividing by 9.", "72/99 = 8/11."],
    },
  },
};

const sharedDbShape = {
  siteSlug: SITE_ID,
  subjectSlug: SUBJECT_ID,
  accountNamespace: "Waldorf English Pathway Supabase",
  accountFields: ["auth.users.email", "guardian_profiles.user_id", "learners.nickname", "learners.school_year"],
  progressFields: ["objective_responses.learner_id", "objective_responses.activity_key", "activity_progress.completed"],
};

window.lessons = lessons;
window.lessonTranslations = lessonTranslations;
window.lessonWorkedSteps = lessonWorkedSteps;
window.extraPracticeBank = extraPracticeBank;
window.sharedDbShape = sharedDbShape;
